stages:
  - test
  - deploy-cn    # 中国服务器部署阶段
  - deploy-global # 全球服务器部署阶段

# ================= 公共配置 =================
.common-deploy:
  stage: test
  tags:
    - deploy
  resource_group: $CI_COMMIT_REF_SLUG
  interruptible: true
  only:
    - main
  before_script:
    - echo "Build project on branch [$CI_COMMIT_BRANCH]"
    - echo "Node version:" && node -v
    - echo "pnpm version:" && pnpm -v
    - pnpm install --no-frozen-lockfile --registry=https://registry.npmmirror.com
    - pnpm build --mode=$BUILD_MODE

# ================= 中国服务器部署 =================
deploy-cn:
  extends: .common-deploy
  stage: deploy-cn
  variables:
    BUILD_MODE: "main"
    HOST: "8.163.35.194"
    USER: "greensmartplanet-gsc"
    PASSWORD: "5lNDZRRI7uTFLTlhSMC1"
    SITE: "gsc.greensmartplanet.cn"
  script:
    - rsync -avz --delete dist/ -e "sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no" $USER@$HOST:/home/$USER/htdocs/$SITE
  after_script:
    - rm -rf "$CI_PROJECT_DIR"/*

# ================= 全球服务器部署 =================
deploy-global:
  extends: .common-deploy
  stage: deploy-global
  variables:
    BUILD_MODE: "main"
    HOST: "103.76.88.125"
    USER: "greensmartplanet-gsc"
    PASSWORD: "aT8DFNQrAizH6IgpHQE4"
    SITE: "gsc.greensmartplanet.com"
  script:
    - rsync -avz --delete dist/ -e "sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no" $USER@$HOST:/home/$USER/htdocs/$SITE
  after_script:
    - rm -rf "$CI_PROJECT_DIR"/*